_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.1
            "8":
                - 1
                - 2
                - 5
                - 12
            "12": 0.19.1
            "13": linux-x86_64
batch_size:
    value: 64
discretization:
    value: dirac
epochs:
    value: 8
learning_rate:
    value: 0.001
model_config:
    value:
        d_model: 128
        dropout: 0.2
        n_blocks: 6
weight_decay:
    value: 0.01
