_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 1
                - 2
                - 13
                - 16
                - 23
                - 24
                - 55
                - 62
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 1
                - 5
                - 12
            "12": 0.19.8
            "13": linux-x86_64
batch_size:
    value: 128
epochs:
    value: 50
learning_rate:
    value: 0.01
loss_function:
    value: nce
model:
    value: ResNet18
momentum:
    value: 0.9
noise_rate:
    value: 0.6
type:
    value: sym
weight_decay:
    value: 0.0001
